log_tools/kismetdb_statistics.cc: use strftime
Building with gcc < 5 (e.g. gcc 4.8) raises the following build failure:

log_tools/kismetdb_statistics.cc: In function 'int main(int, char**)':
log_tools/kismetdb_statistics.cc:206:21: error: 'put_time' is not a member of 'std'
                     std::put_time(&min_tm, "%Y-%m-%d %H:%M:%S"), min_time,
                     ^
log_tools/kismetdb_statistics.cc:207:21: error: 'put_time' is not a member of 'std'
                     std::put_time(&max_tm, "%Y-%m-%d %H:%M:%S"), max_time);
                     ^

This issue is due to a gcc bug
(https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354) which has been
fixed in gcc 5. So replace std::put_time by strftime

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>